### ISSUE TITLE
Create a secondary sub domain for 

### ISSUE THREAD

**Issue by alisman** [cBioPortal/rfc80-team#19]
We need a way to call new our new endpoints on a separate subdomain (but against the same actual api server) in order to prevent fast clickhouse backed endpoints from getting stuck in the queue behind very slow legacy endpoints (browsers only allow a limited number of concurrent requests to a given host.)

genie-public-beta1.cbioportal.org would be fine

**Comment by dippindots** [comment]
`genie-public-beta1.cbioportal.org` is ready and it's using the same backend as `genie-public-beta.cbioportal.org`
