### ISSUE TITLE
SQL error when setting genomic-data-bin-counts filter

### ISSUE THREAD

**Issue by alisman** [cBioPortal/rfc80-team#42]
fetch("https://genie-public-beta1.cbioportal.org/api/column-store/filtered-samples/fetch?", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Not)A;Brand\";v=\"99\", \"Google Chrome\";v=\"127\", \"Chromium\";v=\"127\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "https://genie-public-beta.cbioportal.org/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"genomicDataFilters\":[{\"hugoGeneSymbol\":\"EGFR\",\"profileType\":\"rna_seq_v2_mrna_median_all_sample_ref_normal_Zscores\",\"values\":[{\"start\":-1.4,\"end\":-1.2},{\"start\":-1.2,\"end\":-1},{\"start\":-1,\"end\":-0.8},{\"start\":-0.8,\"end\":-0.6},{\"start\":-0.6,\"end\":-0.4},{\"start\":-0.4,\"end\":-0.2},{\"start\":-0.2,\"end\":0}]}],\"studyIds\":[\"skcm_tcga_pan_can_atlas_2018\",\"stad_tcga_pan_can_atlas_2018\"],\"alterationFilter\":{\"copyNumberAlterationEventTypes\":{\"AMP\":true,\"HOMDEL\":true},\"mutationEventTypes\":{\"any\":true},\"structuralVariants\":null,\"includeDriver\":true,\"includeVUS\":true,\"includeUnknownOncogenicity\":true,\"includeUnknownTier\":true,\"includeGermline\":true,\"includeSomatic\":true,\"includeUnknownStatus\":true,\"tiersBooleanMap\":{}}}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});

**Comment by fuzhaoyuan** [comment]
I think bin-counts is @dippindots?

**Comment by dippindots** [comment]
@alisman Yes this is the numerical filter for the genomic data in progress, so I'm not too suprise to see it failing right now.
