### ISSUE TITLE
Remaining normalization issue with TRUE|true values

### ISSUE THREAD

**Issue by alisman** [cBioPortal/rfc80-team#46]
https://genie-public-beta.cbioportal.org/study/summary?id=genie_public

![image](https://github.com/user-attachments/assets/b24fbc8c-6ecd-453e-8410-3cd7c2c95f86)

**Comment by onursumer** [comment]
<img width="518" alt="Screenshot 2024-08-26 at 6 01 58 PM" src="https://github.com/user-attachments/assets/6a5ef91d-9651-433c-8e60-28b600fe8892">

Can't reproduce this on https://genie-public-beta.cbioportal.org/study/summary?id=genie_public. Maybe a browser cache issue?

**Comment by alisman** [comment]
👍 weird.  i can't reproduce either.
